name: codelab_tests
version: 1.0.0
description: >-
  This isn't a real project. It's just for testing Dart codelab exercises.
environment:
  sdk: '>=2.5.0 <3.0.0'
dev_dependencies:
  matcher: ^0.12.5
  test: ^1.6.9
  dartpad_test:
    git:
      url: git://github.com/RedBrogdon/dartpad_test.git
      path: packages/dartpad_test
