name: flutter_exercise
description: >-
  This isn't a real project. It's just for testing Flutter codelab exercises.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: ^0.12.5
  dartpad_test:
    git:
      url: git://github.com/RedBrogdon/dartpad_test.git
      path: dartpad_test
  dartpad_flutter_test:
    git:
      url: git://github.com/RedBrogdon/dartpad_test.git
      path: dartpad_flutter_test

flutter:
  uses-material-design: true
